name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Jekyll
      uses: ruby/setup-ruby@v1

    - name: Build site
      run: bundle exec jekyll build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: site
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
